### PR TITLE
Do not wrap params into a nested hash (Rails 3.1)

### PR DESCRIPTION
**Pull request by aflatter**
A little work around as long as we use ActionController.

Requests with `Content-Type: application/json` were wrapped into another hash.

### CODE REVIEW

**Comment by drogus** [comment]
This will break 3.0 apps - while I don't want to support 3.0 apps for a longer period of time, I would like to keep it compatible at least for some time - can you check if that method is available before calling it?

**Comment by aflatter** [comment]
Uhm, I think 3.0 behaves nicely which is why we don't need to unset the wrapping:

`if respond_to?(:wrap_parameters)` _should_ mean that 3.0 won't know about anything; I did not test that though.

**Comment by aflatter** [comment]
Oh damn, I shouldn't have pushed to master. I will work on branches by now :)

**Comment by aflatter** [comment]
Let me clean things up first. I will push all my changes in a few days (including a backwards-compatible version of the new query parser, all that rack stuff and probably tests against rails 3.0 and 3.1).

**Pull request closed without merging**
